# Generated by Django 3.0.3 on 2020-03-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='fullname',
            new_name='name',
        ),
    ]
