# Generated by Django 3.0.3 on 2020-03-05 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_auto_20200305_1611'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Student_Number',
        ),
    ]
